### ISSUE TITLE
Please add support for copying a parameter

### ISSUE THREAD

**Issue by bdunderscore** [hai-vr/av3-animator-as-code#25]
Currently there's a state `.Drives` idiom, but there's no way to drive a parameter to be a copy of another currently. This would be handy to have in a gimmick I'm currently developing; I think I can work around it by manually constructing the parameter driver, but it'd be nice not to have to do so.

**Comment by hai-vr** [comment]
It's here but not yet integrated

https://github.com/hai-vr/av3-animator-as-code/commit/44d595892eed827d50ca2426abf4e97d9c06aa5c

**Comment by hai-vr** [comment]
Will be in V1
