### ISSUE TITLE
Sometimes animator states get named "\x01"

### ISSUE THREAD

**Issue by bdunderscore** [hai-vr/av3-animator-as-code#26]
This is probably a unity bug: When a state name is passed in to unity's `StateMachine.NewState`, sometimes it's ignored and the state is given the name `"\x01"` instead. This could be worked around in AAC (I'll probably put together a PR later)

**Comment by hai-vr** [comment]
Did you ever find what caused this issue? I don't know if I've ever caused this to happen

**Comment by bdunderscore** [comment]
Hmm. It's been a while, but looking at my fork it _might_ have been caused by duplicated state names: https://github.com/bdunderscore/av3-animator-as-code/commit/aa7c25c66b401f12ecdf6f92f65960808de2e465#diff-c0df888e97eb2f995df53b8b33a25e7ab2eec823bb65dc5af9588139adcb0c59R201-R207
