### ISSUE TITLE
[Issue]: Too many Assets in a single Container

### ISSUE THREAD

**Issue by HerpDerpinstine** [hai-vr/av3-animator-as-code#4]
https://github.com/hai-vr/av3-animator-as-code/blob/main/Framework/Editor/V0/Aac.cs#L33
https://github.com/hai-vr/av3-animator-as-code/blob/main/Framework/Editor/V0/Aac.cs#L42
https://github.com/hai-vr/av3-animator-as-code/blob/main/Framework/Editor/V0/Aac.cs#L238

There appears to be only a certain amount of assets that can be packed into 1 another.
Somewhere around the neighborhood of 20+ assets.
When there is too many assets in a container the engine starts culling them out by destroying them thereby breaking the setup.

A workaround to this is manually creating the assets in a folder on their own rather than containerizing them.
When I started doing this for AnimationClip creation everything worked properly once again.

An idea for a solution would be doing a size comparison and splitting the 1 container into multiple containers.

**Comment by hai-vr** [comment]
The resolution of this issue on Discord was that the asset container passed to AAC was a newly created asset container (in this case, cloned from an existing one) that had not yet been persisted to disk.

To fix this issue, the asset container must be persisted to disk first, before passing it to AAC. This is known to work with ForceReserializeAssets, and, although not verified, might (?) work with SetDirty.
